# Basic Perceptron -- OR Gate

In [143]:
from numpy import array, dot, random

activation = lambda x: 0 if x < 0 else 1

training_data = [
    (array([0,0,1]), 0),
    (array([0,1,1]), 1),
    (array([1,0,1]), 1),
    (array([1,1,1]), 1),
]

w = random.rand(3)
eta = 0.2
n = 100


def dot_two(x, y):
    if len(x) != len(y):
        raise Exception(f'Vectors are of unequal length: {len(x)}, {len(y)}')
    result = 0
    for i in range(len(x)):
        result += x[i] * y[i]
    return result
            

for i in range(n):
    x, expected = choice(training_data)
    result = dot_two(w, x)
    error = expected - activation(result)
    w += eta * error * x

for x, _ in training_data:
    result = dot(x, w)
    print("{}: {} -> {}".format(x[:2], result, unit_step(result)))

[0 0]: -0.09033867339739271 -> 0
[0 1]: 0.22365357279399828 -> 1
[1 0]: 0.5507015203504058 -> 1
[1 1]: 0.8646937665417969 -> 1
